## Chapter 3 - Exercise 1a: Thực hiện các yêu cầu sau, và đối chiếu với kết quả cho trước

In [5]:
import numpy as np

In [6]:
# Câu 1: Tạo numpy array có giá trị từ 0-9 và lưu vào biến arr
myArr = np.arange(10)

# Hiển thị các phần tử có trong arr
myArr
# Xem kiểu dữ liệu (type) của arr
arrType = myArr.dtype
arrType
# Xem kích thước (shape) của arr
sizes = myArr.shape

sizes


(10,)

<details>
  <summary>Nhấn vào đây để xem kết quả!</summary>
  <pre>[0 1 2 3 4 5 6 7 8 9]
&lt;class 'numpy.ndarray'&gt;
(10,)
</pre>
  
</details>

In [8]:
# Câu 2: Từ array arr ở câu 1 => tạo arr_odd và arr_even 
arr_odd = myArr[myArr%2==0]
arr_even = myArr[myArr%2!=0]


# Hiển thị các phần tử có trong arr_odd và arr_even
print("Odd array")
print(arr_odd)
print("Even array")
print(arr_even)


Odd array
[0 2 4 6 8]
Even array
[1 3 5 7 9]


<details>
  <summary>Nhấn vào đây để xem kết quả!</summary>
  <pre>Odd array:
[1 3 5 7 9]
Event array:
[0 2 4 6 8]
</pre>
  
</details>

In [12]:
# Câu 3: Từ array arr ở câu 1=> tạo arr_update_1 với các phần tử chẵn giữ nguyên, các phần tử lẻ thay bằng 100
arra_update_1 = myArr

arra_update_1 = np.where(arra_update_1%2!=0, 100, arra_update_1)

arra_update_1

# Hiển thị các phần tử có trong arr_update_1


array([  0, 100,   2, 100,   4, 100,   6, 100,   8, 100])

<details>
  <summary>Nhấn vào đây để xem kết quả!</summary>
  <pre>[  0 100   2 100   4 100   6 100   8 100]
</pre>
  
</details>