## Chapter 3 - Exercise 1b: Thực hiện các yêu cầu sau, và đối chiếu với kết quả cho trước

In [10]:
import numpy as np
# Câu 1: Cho 2 array arr_a = [1,2,3,2,3,4,3,4,5,6] và arr_b = [7,2,10,2,7,4,9,4,9,8]
array_a = [1,2,3,2,3,4,3,4,5,6]
array_b = [7,2,10,2,7,4,9,4,9,8]
# Tạo arr_c chỉ lấy duy nhất các phần tử xuất hiện ở cả array arr_a và array arr_b
array_c = np.intersect1d(array_a, array_b)
array_c

array([2, 4])

<details>
  <summary>Nhấn vào đây để xem kết quả!</summary>
  <pre>[2 4]
</pre>
  
</details>

In [7]:
# Câu 2: Từ 2 array arr_a và arr_b ở câu 1 => Tạo array mới arr_d chứa các phần tử chỉ xuất hiện ở array arr_a
array_d = np.setdiff1d(array_a, array_c)
array_d

array([1, 3, 5, 6])

<details>
  <summary>Nhấn vào đây để xem kết quả!</summary>
  <pre>[1 3 5 6]
</pre>
  
</details>

In [24]:
# Câu 3: Cho array arr_e = np.array([2, 6, 1, 9, 10, 3, 27, 8, 6, 25, 16]) 
array_e = np.array([2, 6, 1, 9, 10, 3, 27, 8, 6, 25, 16]) 
# Tạo array arr_f chỉ chứa các phần tử có giá trị từ 5 đến 10 của arr_e
array_f = array_e[ (array_e > 5) & (array_e < 10)]
array_f

array([ 6,  9, 10, 27,  8,  6, 25, 16])

<details>
  <summary>Nhấn vào đây để xem kết quả!</summary>
  <pre>[ 6  9 10  8  6]
</pre>
  
</details>