## Chapter 3 - Exercise 1c: Thực hiện các yêu cầu sau, và đối chiếu với kết quả cho trước

In [109]:
import numpy as np
# Câu 1: Tạo array arr_zeros có 10 phần tử 0, cập nhật phần tử ở vị trí thứ 5 là 1
arr_zeros = np.zeros(10)
arr_zeros[5]=1
arr_zeros



array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

<details>
  <summary>Nhấn vào đây để xem kết quả!</summary>
  <pre>[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
</pre>
  
</details>

In [113]:
# Câu 2: Tạo và in array arr_h có giá trị từ 10 đến 24 
arr_h = np.arange(10,25)

# In danh sách các phần tử theo tứ tự đảo ngược của arr_h vừa tạo
arr_h = arr_h[::-1]
arr_h

array([24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

<details>
  <summary>Nhấn vào đây để xem kết quả!</summary>
  <pre>[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
</pre>
  
</details>

In [128]:
# Câu 3: Cho array arr_k = np.array([1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 0]) 
arr_k = np.array([1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 0])
# Tạo array arr_l từ arr_k với các phần tử khác 0
arr_l = arr_k[arr_k!=0]
arr_l

array([1, 2, 8, 2, 1, 3, 5])

<details>
  <summary>Nhấn vào đây để xem kết quả!</summary>
  <pre>[1 2 0 8 2 0 1 3 0 5 0]
[1 2 8 2 1 3 5]
</pre>
  
</details>

In [134]:
# Câu 4: Từ array arr_l của câu 3, thêm 2 phần tử có giá trị là 10 và 20 vào cuối array
arr_m = np.append(arr_l, [10,20])
arr_m

array([ 1,  2,  8,  2,  1,  3,  5, 10, 20])

<details>
  <summary>Nhấn vào đây để xem kết quả!</summary>
  <pre>[ 1  2  8  2  1  3  5 10 20]
</pre>
  
</details>

In [137]:
# Câu 5: Từ array của câu 4, thêm phần tử có giá trị 100 vào vị trí có index = 5
arr_h = np.insert(arr_m, 5, 100)
arr_h

array([  1,   2,   8,   2,   1, 100,   3,   5,  10,  20])

<details>
  <summary>Nhấn vào đây để xem kết quả!</summary>
  <pre>[  1   2   8   2   1 100   3   5  10  20]
</pre>
  
</details>

In [143]:
# Câu 6: Từ array của câu 5, xóa các phần tử tại vị trí có index = 0, 1, 2
arr_d = np.delete(arr_h, [0,1,2])
arr_d


array([  2,   1, 100,   3,   5,  10,  20])

<details>
  <summary>Nhấn vào đây để xem kết quả!</summary>
  <pre>[  2   1 100   3   5  10  20]
</pre>
  
</details>